"""add is_client to competitors

Revision ID: c028817fb917
Revises: 9a1527b4e016
Create Date: 2026-09-26 07:28:29.216831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c028817fb917'
down_revision: Union[str, Sequence[str], None] = '9a1527b4e016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('is_client', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'is_client')
    # ### end Alembic commands ###
